#
###################################
# Site wide configuration
####################################
#
title:       "Leonids Jekyll theme"
description: "Clean Jekyll blog theme called Leonids."
url:         "http://filype.com"

#
###################################
# Jekyll configuration
####################################
#
timezone:          Auckland/Pacific
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Filype Pereira
  avatar: avatar.jpg
  job: "Software developer"
  bio: "Write about yourself"
  email: "pereira.filype@gmail.com"
  disqus-shortname: filype-blog
  twitter: "FilypePereira"
  facebook:
  google:
    plus:
    analytics: "UA-71295675-1"
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: "fpereira1"
  stackoverflow: "280842/filype" #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
